name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Builds
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Restore Deps
        run: |
          pushd server
          dotnet restore
          popd

          pushd client
          yarn install
          popd

          yarn install

      - id: create-release
        run: ./create-release.ps1
        shell: pwsh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.create-release.outputs.VERSION }}
          tag_name: v${{ steps.create-release.outputs.VERSION }}
          prerelease: false
          files: |
            dist/vscode-loretta-*.vsix
